/-
  FrobeniusDescentP/Tameness.lean
  ===============================

  Parametric port of `PolyClone.Tameness` from `ZMod 2` coefficients to a
  perfect field `Fq` of characteristic 2: the diagonal subalgebra
  `Diag Fq = Fq[X+Y]`, the substitution-rigidity predicate `Tame`
  (property (†) of the paper), and the master reduction

      `master : Tame q → X+Y ∉ Clo q`

  (a clone induction with invariant "not diagonal, or constant").

  Explicitness convention: `Fq` is EXPLICIT in `Diag` (call sites write
  `Diag Fq`, matching `F Fq` / `evC Fq` from `Defs`); it is IMPLICIT in
  everything else (`IsConst`, `Tame`, the atom lemmas, `bind₁_const_const`,
  `Pinv`, `master`), where it is inferable from the arguments/goal.
-/
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.Algebra.MvPolynomial.Monad
import Mathlib.RingTheory.Adjoin.Basic
import Mathlib.Algebra.CharP.Two
import PolyClone.Perfect.Defs
import PolyClone.CloAddMul

namespace PolyClone.Perfect

open MvPolynomial
open PolyClone.CloAddMul
open scoped Classical

set_option linter.unusedSectionVars false

variable (Fq : Type) [Field Fq] [CharP Fq 2] [PerfectRing Fq 2]

/-- `Diag Fq = Fq[X+Y]`, the subalgebra generated by `X+Y`.
    `Fq` is explicit: call sites write `Diag Fq`. -/
noncomputable def Diag : Subalgebra Fq (F Fq) :=
  Algebra.adjoin Fq {(X 0 + X 1 : F Fq)}

variable {Fq}

/-- A polynomial is constant. -/
def IsConst (p : F Fq) : Prop := ∃ c : Fq, p = C c

/-- **Tameness.** A nonconstant `q`-value lying in `Fq[X+Y]` forces both
    inputs into `Fq[X+Y]`. -/
def Tame (q : F Fq) : Prop :=
  ∀ α β : F Fq, ¬ IsConst (bind₁ ![α, β] q) → bind₁ ![α, β] q ∈ Diag Fq →
    α ∈ Diag Fq ∧ β ∈ Diag Fq

/-! ## Atom / membership facts -/

@[simp] lemma XplusY_mem_Diag : (X 0 + X 1 : F Fq) ∈ Diag Fq :=
  Algebra.subset_adjoin (Set.mem_singleton _)

lemma const_mem_Diag (c : Fq) : (C c : F Fq) ∈ Diag Fq :=
  Subalgebra.algebraMap_mem _ c

/-- `X` is not a polynomial in `X+Y` (the `X ↔ Y` swap fixes `Diag` but not `X`). -/
lemma X0_not_mem_Diag : (X 0 : F Fq) ∉ Diag Fq := by
  intro h
  set f : F Fq →ₐ[Fq] F Fq := aeval ![0, X 0] with hf
  set g : F Fq →ₐ[Fq] F Fq := aeval ![X 0, 0] with hg
  have hgen : ({(X 0 + X 1 : F Fq)} : Set (F Fq)).EqOn f g := by
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst hx
    simp [hf, hg]
  have hle : Diag Fq ≤ AlgHom.equalizer f g := by
    rw [Diag]; exact AlgHom.adjoin_le_equalizer f g hgen
  have heq : f (X 0) = g (X 0) := hle h
  simp only [hf, hg, aeval_X, Matrix.cons_val_zero] at heq
  exact (X_ne_zero (0 : Fin 2)) heq.symm

lemma X1_not_mem_Diag : (X 1 : F Fq) ∉ Diag Fq := by
  intro h
  set f : F Fq →ₐ[Fq] F Fq := aeval ![0, X 0] with hf
  set g : F Fq →ₐ[Fq] F Fq := aeval ![X 0, 0] with hg
  have hgen : ({(X 0 + X 1 : F Fq)} : Set (F Fq)).EqOn f g := by
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst hx
    simp [hf, hg]
  have hle : Diag Fq ≤ AlgHom.equalizer f g := by
    rw [Diag]; exact AlgHom.adjoin_le_equalizer f g hgen
  have heq : f (X 1) = g (X 1) := hle h
  simp only [hf, hg, aeval_X, Matrix.cons_val_one, Matrix.cons_val_zero] at heq
  exact (X_ne_zero (0 : Fin 2)) heq

lemma XplusY_not_isConst : ¬ IsConst (X 0 + X 1 : F Fq) := by
  rintro ⟨c, hc⟩
  have h := congrArg (coeff (Finsupp.single 0 1)) hc
  rw [coeff_add, coeff_X, coeff_X', coeff_C] at h
  have h1 : ¬ (Finsupp.single (1 : Fin 2) 1 = Finsupp.single (0 : Fin 2) 1) := by
    simp [Finsupp.single_left_inj]
  have h2 : ¬ ((0 : Fin 2 →₀ ℕ) = Finsupp.single (0 : Fin 2) 1) := by
    simp [eq_comm, Finsupp.single_eq_zero]
  rw [if_neg h1, if_neg h2] at h
  simp at h

/-- A substitution with constant inputs yields a constant. -/
lemma bind₁_const_const (q : F Fq) (a b : Fq) : IsConst (bind₁ ![C a, C b] q) := by
  refine ⟨aeval ![a, b] q, ?_⟩
  rw [← aeval_eq_bind₁]
  have he : (![C a, C b] : Fin 2 → F Fq) = fun i => (Algebra.ofId Fq (F Fq)) (![a, b] i) := by
    funext i; fin_cases i <;> rfl
  rw [he, ← comp_aeval]
  rfl

/-! ## Master reduction: `Tame q ⟹ X+Y ∉ Clo q` -/

/-- The clone-invariant: each reachable polynomial is either outside `Fq[X+Y]`
    or constant. -/
def Pinv (g : F Fq) : Prop := g ∉ Diag Fq ∨ IsConst g

theorem master (q : F Fq) (ht : Tame q) :
    ¬ PolyClone.CloAddMul.Clo q (X 0 + X 1) := by
  -- It suffices to show `Pinv` holds on all of `Clo q`, since `X+Y` violates it.
  have hPreserved : ∀ g : F Fq, Clo q g → Pinv g := by
    intro g hg
    induction hg with
    | atomX => exact Or.inl X0_not_mem_Diag
    | atomY => exact Or.inl X1_not_mem_Diag
    | const c => exact Or.inr ⟨c, rfl⟩
    | @sub α β _ _ ihα ihβ =>
        -- Suppose `bind₁ ![α,β] q` fails `Pinv`: it is in `Diag` and nonconstant.
        by_contra hbad
        rw [Pinv, not_or] at hbad
        obtain ⟨hmem, hnc⟩ := hbad
        rw [not_not] at hmem
        have hncf : ¬ IsConst (bind₁ ![α, β] q) := hnc
        obtain ⟨hαD, hβD⟩ := ht α β hncf hmem
        -- From the IHs, `α ∈ Diag` (so not the first disjunct) ⟹ `α` constant; same for `β`.
        have hαc : IsConst α := ihα.resolve_left (by simpa using hαD)
        have hβc : IsConst β := ihβ.resolve_left (by simpa using hβD)
        obtain ⟨a, rfl⟩ := hαc
        obtain ⟨b, rfl⟩ := hβc
        exact hncf (bind₁_const_const q a b)
  -- `X+Y` is in `Diag` and nonconstant, so it cannot be in `Clo q`.
  intro hxy
  rcases hPreserved _ hxy with h | h
  · exact h XplusY_mem_Diag
  · exact XplusY_not_isConst h

end PolyClone.Perfect
