/-
  PolyClone.Naturals
  =====================================

  Impossibility theorems for clones generated by a single total binary
  operator on ℕ. The headline result (`polynomial_does_not_reach_both`):

    For any *polynomial* binary operator `⊙ : ℕ × ℕ → ℕ` (i.e., `⊙` is
    the evaluation of some `p : MvPolynomial (Fin 2) ℕ`), not both of
    `+` and `·` lie in the clone of `⟨⊙, ℕ-constants⟩`.

  The polynomial restriction is essential: without it, Sierpiński-style
  pair encoding via Cantor pairing yields a (non-polynomial, piecewise)
  `⊙` whose clone contains both `+` and `·` (`⊙(1, a) = ⟨3, a⟩` then
  `⊙(⟨3, a⟩, b) = a + b`; similarly for `·` via a different tag). The
  polynomial qualifier rules out this decoding-based trick because
  decoding from Cantor pairs is not polynomial.

  Three concrete-generator instances are proven independently of the
  master theorem (they use lighter machinery — affine forms and
  multiplicative-cross invariants):

    1. `add_does_not_reach_mul` — every `(· + ·)`-term is `A·x + B·y + C`.
    2. `mul_does_not_reach_add` — every `(· * ·)`-term satisfies the
       Cross invariant `f(0,0)·f(1,1) = f(1,0)·f(0,1)`, which `+` fails.
    3. `opAddMul_does_not_reach_add` — the same with ShiftedCross.

  These are corollaries of the more general clone-invariant theorems
  `affine_does_not_reach_mul`, `cross_preserving_does_not_reach_add`,
  and `shiftedCross_preserving_does_not_reach_add`.

  The master theorem `polynomial_does_not_reach_both` proceeds by case
  split on the underlying polynomial's totalDegree:
    - `totalDegree ≤ 1`: `⊙` is affine, so the affine-vs-mul theorem
      kills the multiplication side.
    - `totalDegree ≥ 2`: strong induction on term size shows `⊙` can't
      reach `+`. The induction step decomposes the realizing polynomial
      via `bind₁` and dispatches on which subterm-polynomial is constant.
      See the strategy block just before the master theorem for details.

  This file uses a custom `Term` inductive type rather than Mathlib's
  `FirstOrder.Language.Term`, to keep the proofs focused. Integration
  with the project's general framework is left to follow-up files.
-/

import Mathlib.Data.Nat.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Fintype.Fin
import Mathlib.Data.Fin.VecNotation
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Linarith
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.Algebra.MvPolynomial.Monad
import Mathlib.Algebra.MvPolynomial.Degrees
import Mathlib.Algebra.MvPolynomial.NoZeroDivisors

namespace PolyClone.Naturals

/-! ## Term language

A term over a single binary operator with ℕ-valued constants and
variables in `α`. Every term is a finite tree. -/

/-- A term over a single binary operator with ℕ-constants. -/
inductive Term (α : Type) where
  /-- A variable. -/
  | var : α → Term α
  /-- A natural-number constant. -/
  | const : ℕ → Term α
  /-- An application of the binary operator. -/
  | op : Term α → Term α → Term α

/-- Size of a term (number of operator applications). Used for strong
    induction in the polynomial-impossibility master theorem. -/
def Term.size {α} : Term α → ℕ
  | .var _ => 0
  | .const _ => 0
  | .op s u => s.size + u.size + 1

/-- Evaluate a term, given a binary operator and a variable assignment. -/
def Term.eval {α} (op : ℕ → ℕ → ℕ) (v : α → ℕ) : Term α → ℕ
  | .var a => v a
  | .const n => n
  | .op s t => op (s.eval op v) (t.eval op v)

/-- A binary function `f : ℕ → ℕ → ℕ` is *reached* by `op` (with the
    standard finite constants implicit in `Term`) if there is a term
    over `op` whose evaluation matches `f` everywhere. -/
def Reaches (op : ℕ → ℕ → ℕ) (f : ℕ → ℕ → ℕ) : Prop :=
  ∃ t : Term (Fin 2), ∀ a b : ℕ, t.eval op ![a, b] = f a b

/-! ## Target functions: addition and multiplication on ℕ -/

/-- Addition as a function `ℕ → ℕ → ℕ`. -/
def addFn : ℕ → ℕ → ℕ := (· + ·)

/-- Multiplication as a function `ℕ → ℕ → ℕ`. -/
def mulFn : ℕ → ℕ → ℕ := (· * ·)

/-! ## General theorem 1: ℕ-affine operators don't reach `·`

A binary operator `⊙ : ℕ × ℕ → ℕ` is *ℕ-affine* if it has the form
`⊙(x, y) = α·x + β·y + γ` for some `α, β, γ ∈ ℕ`. We prove:

  - For any ℕ-affine ⊙, every term over `⊙` evaluates to a ℕ-affine
    function.
  - Hence `·` is not reachable from any ℕ-affine ⊙ — it has a
    non-trivial cross-term that no ℕ-affine function exhibits.

The original `add_does_not_reach_mul` is the case `α = β = 1, γ = 0`.
-/

/-- A binary operator on ℕ is *ℕ-affine* if it equals
    `α·x + β·y + γ` for some `α, β, γ ∈ ℕ`. -/
def IsNatAffine (op : ℕ → ℕ → ℕ) : Prop :=
  ∃ α β γ : ℕ, ∀ x y : ℕ, op x y = α * x + β * y + γ

/-- Every term over a ℕ-affine operator evaluates to a ℕ-affine
    function of its inputs. -/
theorem affine_term_is_affine {op : ℕ → ℕ → ℕ} (h_aff : IsNatAffine op)
    (t : Term (Fin 2)) :
    ∃ A B C : ℕ, ∀ a b : ℕ, t.eval op ![a, b] = A * a + B * b + C := by
  obtain ⟨α, β, γ, hop⟩ := h_aff
  induction t with
  | var i =>
    fin_cases i
    · exact ⟨1, 0, 0, by intro a b; simp [Term.eval]⟩
    · exact ⟨0, 1, 0, by intro a b; simp [Term.eval]⟩
  | const n =>
    exact ⟨0, 0, n, by intro a b; simp [Term.eval]⟩
  | op s t ihs iht =>
    obtain ⟨As, Bs, Cs, hs⟩ := ihs
    obtain ⟨At, Bt, Ct, ht⟩ := iht
    refine ⟨α * As + β * At, α * Bs + β * Bt, α * Cs + β * Ct + γ, ?_⟩
    intro a b
    simp only [Term.eval, hs a b, ht a b, hop]
    ring

/-- **Theorem.** No ℕ-affine operator reaches multiplication. -/
theorem affine_does_not_reach_mul {op : ℕ → ℕ → ℕ} (h : IsNatAffine op) :
    ¬ Reaches op mulFn := by
  rintro ⟨t, h_t⟩
  obtain ⟨A, B, C, h_form⟩ := affine_term_is_affine h t
  have h00 := h_t 0 0
  have h10 := h_t 1 0
  have h01 := h_t 0 1
  have h11 := h_t 1 1
  rw [h_form] at h00 h10 h01 h11
  simp [mulFn] at h00 h10 h01 h11
  omega

/-! ### Corollary: addition does not reach multiplication

Recovers the original `add_does_not_reach_mul` from the general theorem.
-/

/-- Addition is ℕ-affine with `α = β = 1, γ = 0`. -/
theorem addFn_isAffine : IsNatAffine addFn :=
  ⟨1, 1, 0, by intros; simp [addFn]⟩

/-- **Corollary.** Addition does not reach multiplication. -/
theorem add_does_not_reach_mul : ¬ Reaches addFn mulFn :=
  affine_does_not_reach_mul addFn_isAffine

/-! ## General theorem 2: Cross-preserving operators don't reach `+`

A function `f : ℕ → ℕ → ℕ` satisfies the *cross relation* if
`f(0,0) · f(1,1) = f(1,0) · f(0,1)`. This is a clone-theoretic
invariant: it holds for projections, constants, and is preserved
by multiplication-like operators. It fails for `+`
(since `0 · 2 = 0 ≠ 1 = 1 · 1`).

We prove the generic clone-closure result: for any `⊙` preserving
Cross, every term over `⊙` satisfies Cross. Hence `+` is unreachable
from any such `⊙`. Multiplication is the canonical example,
recovering `mul_does_not_reach_add` as a corollary.
-/

/-- The *cross relation* on a binary function `f : ℕ → ℕ → ℕ`. -/
def Cross (f : ℕ → ℕ → ℕ) : Prop :=
  f 0 0 * f 1 1 = f 1 0 * f 0 1

theorem Cross.const (c : ℕ) : Cross (fun _ _ : ℕ => c) := by
  unfold Cross; ring

theorem Cross.proj_left : Cross (fun a _ : ℕ => a) := by
  unfold Cross; ring

theorem Cross.proj_right : Cross (fun _ b : ℕ => b) := by
  unfold Cross; ring

/-- If `op` preserves the Cross relation, every term over `op` satisfies it. -/
theorem term_cross_invariant {op : ℕ → ℕ → ℕ}
    (hop : ∀ f g : ℕ → ℕ → ℕ, Cross f → Cross g →
           Cross (fun a b => op (f a b) (g a b)))
    (t : Term (Fin 2)) :
    Cross (fun a b => t.eval op ![a, b]) := by
  induction t with
  | var i =>
    fin_cases i
    · change Cross (fun a _ : ℕ => a); exact Cross.proj_left
    · change Cross (fun _ b : ℕ => b); exact Cross.proj_right
  | const n =>
    change Cross (fun _ _ : ℕ => n); exact Cross.const n
  | op s t ihs iht =>
    change Cross (fun a b => op (Term.eval op ![a, b] s) (Term.eval op ![a, b] t))
    exact hop _ _ ihs iht

/-- Addition violates Cross: `0 · 2 = 0 ≠ 1 = 1 · 1`. -/
theorem addFn_not_cross : ¬ Cross addFn := by
  unfold Cross addFn
  decide

/-- **Generic theorem.** Any operator preserving the Cross relation does
    not reach addition. -/
theorem cross_preserving_does_not_reach_add {op : ℕ → ℕ → ℕ}
    (hop : ∀ f g : ℕ → ℕ → ℕ, Cross f → Cross g →
           Cross (fun a b => op (f a b) (g a b))) :
    ¬ Reaches op addFn := by
  rintro ⟨t, h_t⟩
  apply addFn_not_cross
  have h_eq : (fun a b => Term.eval op ![a, b] t) = addFn := by
    funext a b; exact h_t a b
  have h_cross := term_cross_invariant hop t
  rwa [h_eq] at h_cross

/-! ### Corollary: multiplication does not reach addition -/

/-- Multiplication preserves Cross. -/
theorem mulFn_preserves_cross :
    ∀ f g : ℕ → ℕ → ℕ, Cross f → Cross g →
    Cross (fun a b => mulFn (f a b) (g a b)) := by
  intro f g hf hg
  show f 0 0 * g 0 0 * (f 1 1 * g 1 1) = f 1 0 * g 1 0 * (f 0 1 * g 0 1)
  unfold Cross at hf hg
  calc f 0 0 * g 0 0 * (f 1 1 * g 1 1)
      = (f 0 0 * f 1 1) * (g 0 0 * g 1 1) := by ring
    _ = (f 1 0 * f 0 1) * (g 1 0 * g 0 1) := by rw [hf, hg]
    _ = f 1 0 * g 1 0 * (f 0 1 * g 0 1) := by ring

/-- **Corollary.** Multiplication does not reach addition. -/
theorem mul_does_not_reach_add : ¬ Reaches mulFn addFn :=
  cross_preserving_does_not_reach_add mulFn_preserves_cross

/-! ## General theorem 3: ShiftedCross-preserving operators don't reach `+`

A function `f : ℕ → ℕ → ℕ` satisfies the *shifted cross relation* if
`(f(0,0) + 1) · (f(1,1) + 1) = (f(1,0) + 1) · (f(0,1) + 1)`. Equivalent
to `Cross (f + 1)` (componentwise shift). Preserved by operators that
look multiplicative after a `+1` shift, like `⊙(x, y) = x + y + xy =
(x + 1)(y + 1) − 1`.

`+` fails this too: `(0+1)(2+1) = 3 ≠ 4 = (1+1)(1+1)`.
-/

/-- The shifted cross relation. -/
def ShiftedCross (f : ℕ → ℕ → ℕ) : Prop :=
  (f 0 0 + 1) * (f 1 1 + 1) = (f 1 0 + 1) * (f 0 1 + 1)

theorem ShiftedCross.const (c : ℕ) : ShiftedCross (fun _ _ : ℕ => c) := by
  unfold ShiftedCross; ring

theorem ShiftedCross.proj_left : ShiftedCross (fun a _ : ℕ => a) := by
  unfold ShiftedCross; ring

theorem ShiftedCross.proj_right : ShiftedCross (fun _ b : ℕ => b) := by
  unfold ShiftedCross; ring

/-- If `op` preserves the shifted cross relation, every term over `op`
    satisfies it. -/
theorem term_shiftedCross_invariant {op : ℕ → ℕ → ℕ}
    (hop : ∀ f g : ℕ → ℕ → ℕ, ShiftedCross f → ShiftedCross g →
           ShiftedCross (fun a b => op (f a b) (g a b)))
    (t : Term (Fin 2)) :
    ShiftedCross (fun a b => t.eval op ![a, b]) := by
  induction t with
  | var i =>
    fin_cases i
    · change ShiftedCross (fun a _ : ℕ => a); exact ShiftedCross.proj_left
    · change ShiftedCross (fun _ b : ℕ => b); exact ShiftedCross.proj_right
  | const n =>
    change ShiftedCross (fun _ _ : ℕ => n); exact ShiftedCross.const n
  | op s t ihs iht =>
    change ShiftedCross
      (fun a b => op (Term.eval op ![a, b] s) (Term.eval op ![a, b] t))
    exact hop _ _ ihs iht

/-- Addition violates ShiftedCross: `(0+1)(2+1) = 3 ≠ 4 = (1+1)(1+1)`. -/
theorem addFn_not_shiftedCross : ¬ ShiftedCross addFn := by
  unfold ShiftedCross addFn
  decide

/-- **Generic theorem.** Any operator preserving ShiftedCross does
    not reach addition. -/
theorem shiftedCross_preserving_does_not_reach_add {op : ℕ → ℕ → ℕ}
    (hop : ∀ f g : ℕ → ℕ → ℕ, ShiftedCross f → ShiftedCross g →
           ShiftedCross (fun a b => op (f a b) (g a b))) :
    ¬ Reaches op addFn := by
  rintro ⟨t, h_t⟩
  apply addFn_not_shiftedCross
  have h_eq : (fun a b => Term.eval op ![a, b] t) = addFn := by
    funext a b; exact h_t a b
  have h_sc := term_shiftedCross_invariant hop t
  rwa [h_eq] at h_sc

/-! ### Corollary: `x + y + xy` does not reach addition -/

/-- The operator `⊙(x, y) = x + y + xy`, the shift-conjugate of mul. -/
def opAddMul : ℕ → ℕ → ℕ := fun x y => x + y + x * y

/-- `opAddMul` preserves ShiftedCross: the `+1` shift makes it
    multiplicative, since `opAddMul x y + 1 = (x + 1)(y + 1)`. -/
theorem opAddMul_preserves_shiftedCross :
    ∀ f g : ℕ → ℕ → ℕ, ShiftedCross f → ShiftedCross g →
    ShiftedCross (fun a b => opAddMul (f a b) (g a b)) := by
  intro f g hf hg
  show (opAddMul (f 0 0) (g 0 0) + 1) * (opAddMul (f 1 1) (g 1 1) + 1) =
       (opAddMul (f 1 0) (g 1 0) + 1) * (opAddMul (f 0 1) (g 0 1) + 1)
  unfold opAddMul
  have key : ∀ x y : ℕ, x + y + x * y + 1 = (x + 1) * (y + 1) := by intros; ring
  rw [key, key, key, key]
  unfold ShiftedCross at hf hg
  calc (f 0 0 + 1) * (g 0 0 + 1) * ((f 1 1 + 1) * (g 1 1 + 1))
      = ((f 0 0 + 1) * (f 1 1 + 1)) * ((g 0 0 + 1) * (g 1 1 + 1)) := by ring
    _ = ((f 1 0 + 1) * (f 0 1 + 1)) * ((g 1 0 + 1) * (g 0 1 + 1)) := by rw [hf, hg]
    _ = (f 1 0 + 1) * (g 1 0 + 1) * ((f 0 1 + 1) * (g 0 1 + 1)) := by ring

/-- **Corollary.** `x + y + xy` does not reach addition. -/
theorem opAddMul_does_not_reach_add : ¬ Reaches opAddMul addFn :=
  shiftedCross_preserving_does_not_reach_add opAddMul_preserves_shiftedCross

/-! ## Headline theorem: no polynomial `⊙` on `ℕ` reaches both `+` and `·`

The proof requires several structural lemmas about `MvPolynomial (Fin 2) ℕ`
(growth bound, bind₁ degree, no-cancellation, monomial decomposition).
We build them up below and stitch them together in the master theorem.

Outline:
* If `p.totalDegree ≤ 1`, `⊙` is ℕ-affine (its evaluation has the form
  `α·a + β·b + γ`), so `affine_does_not_reach_mul` rules out `·`.
* If `p.totalDegree ≥ 2`, strong induction on term size shows `⊙` can't
  reach `+`. The `.op s u` step computes the realizing polynomial via
  `bind₁` and case-splits on whether the subterm polynomials are constant.
  See the strategy block at the master theorem for the full case tree.

Key MvPolynomial facts proven below:
* `polynomial_term_realizes_poly` — terms compile to polynomials via `bind₁`.
* `bind₁_totalDegree_ge_of_nonconstant` — degree-preservation for `bind₁`.
* `aeval_n_n_ge_n_pow_totalDegree` — diagonal growth bound on `ℕ`.
* `aeval_of_totalDegree_le_one` — affine extraction from low-degree polys.
-/

open MvPolynomial in
/-- A binary operator on `ℕ` is *polynomial* if it equals the evaluation
    of some `MvPolynomial (Fin 2) ℕ`. -/
def IsPolynomialNat (op : ℕ → ℕ → ℕ) : Prop :=
  ∃ p : MvPolynomial (Fin 2) ℕ, ∀ a b : ℕ, op a b = aeval ![a, b] p

/-- Every term over a polynomial `⊙` realizes some `MvPolynomial`. The
    realizing polynomial is built by substituting subterm polynomials
    into `⊙`'s polynomial via `bind₁`. -/
theorem polynomial_term_realizes_poly {op : ℕ → ℕ → ℕ} (h : IsPolynomialNat op)
    (t : Term (Fin 2)) :
    ∃ q : MvPolynomial (Fin 2) ℕ,
      ∀ v : Fin 2 → ℕ, t.eval op v = MvPolynomial.aeval v q := by
  obtain ⟨p, hp⟩ := h
  induction t with
  | var i =>
    refine ⟨MvPolynomial.X i, ?_⟩
    intro v
    simp [Term.eval]
  | const n =>
    refine ⟨MvPolynomial.C n, ?_⟩
    intro v
    simp [Term.eval]
  | op s u ihs ihu =>
    obtain ⟨qs, hqs⟩ := ihs
    obtain ⟨qu, hqu⟩ := ihu
    refine ⟨MvPolynomial.bind₁ ![qs, qu] p, ?_⟩
    intro v
    show op (s.eval op v) (u.eval op v) = MvPolynomial.aeval v _
    rw [hp (s.eval op v) (u.eval op v), MvPolynomial.aeval_bind₁]
    have h_args :
        (![s.eval op v, u.eval op v] : Fin 2 → ℕ) =
        fun i => MvPolynomial.aeval v ((![qs, qu] : Fin 2 → MvPolynomial (Fin 2) ℕ) i) := by
      funext i; fin_cases i
      · simp [hqs v]
      · simp [hqu v]
    rw [h_args]

/-- For ℕ-MvPolynomials, the support is preserved under addition: no
    cancellation can occur with non-negative coefficients. -/
private lemma totalDegree_le_add_left_nat {σ : Type*} (p q : MvPolynomial σ ℕ) :
    p.totalDegree ≤ (p + q).totalDegree := by
  apply Finset.sup_le
  intro d hd
  refine Finset.le_sup (f := fun s => ∑ i ∈ s.support, s i) (b := d) ?_
  rw [MvPolynomial.mem_support_iff] at hd ⊢
  rw [MvPolynomial.coeff_add]
  omega

/-- For `p : MvPolynomial (Fin 2) ℕ`, substituting into non-constant
    polynomials does not reduce total degree. -/
theorem bind₁_totalDegree_ge_of_nonconstant
    (p g_s g_u : MvPolynomial (Fin 2) ℕ)
    (hs : g_s.totalDegree ≥ 1) (hu : g_u.totalDegree ≥ 1) :
    p.totalDegree ≤ (MvPolynomial.bind₁ ![g_s, g_u] p).totalDegree := by
  induction p using MvPolynomial.induction_on with
  | C a => simp [MvPolynomial.totalDegree_C]
  | add q r ihq ihr =>
    rw [map_add]
    calc (q + r).totalDegree
        ≤ max q.totalDegree r.totalDegree := MvPolynomial.totalDegree_add _ _
      _ ≤ max (MvPolynomial.bind₁ ![g_s, g_u] q).totalDegree
              (MvPolynomial.bind₁ ![g_s, g_u] r).totalDegree :=
        max_le_max ihq ihr
      _ ≤ (MvPolynomial.bind₁ ![g_s, g_u] q +
            MvPolynomial.bind₁ ![g_s, g_u] r).totalDegree := by
        apply max_le
        · exact totalDegree_le_add_left_nat _ _
        · rw [add_comm]; exact totalDegree_le_add_left_nat _ _
  | mul_X q i ih =>
    rw [map_mul, MvPolynomial.bind₁_X_right]
    by_cases hq : q = 0
    · subst hq; simp
    · have h_gi_deg :
          1 ≤ ((![g_s, g_u] : Fin 2 → MvPolynomial (Fin 2) ℕ) i).totalDegree := by
        fin_cases i
        · simpa using hs
        · simpa using hu
      have h_gi_ne : ((![g_s, g_u] : Fin 2 → MvPolynomial (Fin 2) ℕ) i) ≠ 0 := by
        intro h
        rw [h, MvPolynomial.totalDegree_zero] at h_gi_deg
        omega
      have h_xi_ne : (MvPolynomial.X i : MvPolynomial (Fin 2) ℕ) ≠ 0 :=
        MvPolynomial.X_ne_zero _
      have h_bq_ne : MvPolynomial.bind₁ ![g_s, g_u] q ≠ 0 := by
        by_cases h_qd : q.totalDegree = 0
        · have h_eq : q = MvPolynomial.C (q.coeff 0) :=
            MvPolynomial.totalDegree_eq_zero_iff_eq_C.mp h_qd
          have h_cne : q.coeff 0 ≠ 0 := by
            intro h
            apply hq
            rw [h_eq, h, map_zero]
          rw [h_eq, MvPolynomial.bind₁_C_right]
          exact fun h => h_cne (MvPolynomial.C_eq_zero.mp h)
        · have h_qd_ge : 1 ≤ q.totalDegree := Nat.one_le_iff_ne_zero.mpr h_qd
          have : 1 ≤ (MvPolynomial.bind₁ ![g_s, g_u] q).totalDegree :=
            le_trans h_qd_ge ih
          intro h_zero
          rw [h_zero, MvPolynomial.totalDegree_zero] at this
          omega
      rw [MvPolynomial.totalDegree_mul_of_isDomain hq h_xi_ne,
          MvPolynomial.totalDegree_mul_of_isDomain h_bq_ne h_gi_ne,
          MvPolynomial.totalDegree_X i]
      omega

/-! ### Growth bound and affine extraction

The growth lemma: for `q : MvPolynomial (Fin 2) ℕ` with non-empty support,
evaluation at `(n, n)` is bounded below by `n^q.totalDegree`. This is
the "no cancellation on ℕ" content: a max-degree monomial contributes
`≥ n^totalDegree`, and other monomials add non-negatively.
-/

/-- The product `∏ i ∈ s, n^(d i)` equals `n^(∑ i ∈ s, d i)`. -/
private lemma prod_pow_const_eq_pow_sum (s : Finset (Fin 2)) (d : Fin 2 → ℕ) (n : ℕ) :
    ∏ i ∈ s, n ^ d i = n ^ ∑ i ∈ s, d i := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.prod_insert ha, Finset.sum_insert ha, ih, pow_add]

/-- Growth bound: for non-zero `q ∈ MvPolynomial (Fin 2) ℕ`, evaluation at
    `(n, n)` for `n ≥ 1` is at least `n^q.totalDegree`. The max-degree
    monomial in the support contributes at least `n^totalDegree` (since
    its coefficient is `≥ 1`); other monomials add non-negatively. -/
private lemma aeval_n_n_ge_n_pow_totalDegree
    (q : MvPolynomial (Fin 2) ℕ) (hq : q ≠ 0) (n : ℕ) (hn : 1 ≤ n) :
    n ^ q.totalDegree ≤ MvPolynomial.aeval (![n, n] : Fin 2 → ℕ) q := by
  classical
  have h_supp : q.support.Nonempty := by
    rw [Finset.nonempty_iff_ne_empty]
    intro h
    exact hq (MvPolynomial.support_eq_empty.mp h)
  obtain ⟨d_max, hd_mem, hd_max⟩ :=
    q.support.exists_max_image (fun s => ∑ i ∈ s.support, s i) h_supp
  have hd_eq : ∑ i ∈ d_max.support, d_max i = q.totalDegree := by
    unfold MvPolynomial.totalDegree
    apply le_antisymm
    · exact Finset.le_sup (f := fun s => ∑ i ∈ s.support, s i) hd_mem
    · exact Finset.sup_le hd_max
  have h_coeff_ge : 1 ≤ q.coeff d_max := by
    rw [MvPolynomial.mem_support_iff] at hd_mem
    omega
  -- Express aeval as a sum and bound below by the d_max contribution
  rw [show MvPolynomial.aeval (![n, n] : Fin 2 → ℕ) q =
        ∑ d ∈ q.support, q.coeff d * ∏ i ∈ d.support, (![n, n] : Fin 2 → ℕ) i ^ d i from by
    rw [MvPolynomial.aeval_def, MvPolynomial.eval₂_eq]
    simp [RingHom.id_apply]]
  -- d_max contribution is q.coeff d_max * n^q.totalDegree ≥ n^q.totalDegree
  have h_dmax_contrib :
      n ^ q.totalDegree ≤ q.coeff d_max * ∏ i ∈ d_max.support,
                                            (![n, n] : Fin 2 → ℕ) i ^ d_max i := by
    have h_prod : ∏ i ∈ d_max.support, (![n, n] : Fin 2 → ℕ) i ^ d_max i =
                  n ^ q.totalDegree := by
      rw [← hd_eq]
      rw [show (fun i => (![n, n] : Fin 2 → ℕ) i ^ d_max i) =
             fun i => n ^ d_max i from by funext i; fin_cases i <;> simp]
      exact prod_pow_const_eq_pow_sum _ _ _
    rw [h_prod]
    calc n ^ q.totalDegree = 1 * n ^ q.totalDegree := by ring
      _ ≤ q.coeff d_max * n ^ q.totalDegree := Nat.mul_le_mul_right _ h_coeff_ge
  -- The sum is at least the d_max contribution (other terms are ≥ 0)
  calc n ^ q.totalDegree
      ≤ q.coeff d_max * ∏ i ∈ d_max.support,
                          (![n, n] : Fin 2 → ℕ) i ^ d_max i := h_dmax_contrib
    _ ≤ ∑ d ∈ q.support, q.coeff d * ∏ i ∈ d.support,
                            (![n, n] : Fin 2 → ℕ) i ^ d i := by
      exact Finset.single_le_sum (f := fun d => q.coeff d *
              ∏ i ∈ d.support, (![n, n] : Fin 2 → ℕ) i ^ d i)
              (fun _ _ => Nat.zero_le _) hd_mem

/-! ### Affine extraction for low-degree polynomials -/

/-- A `Finsupp (Fin 2) ℕ` of total weight ≤ 1 is `0`, `single 0 1`, or `single 1 1`. -/
private lemma sum_ge_two_of_not_low {s : Fin 2 →₀ ℕ}
    (h0 : s ≠ 0)
    (h1 : s ≠ Finsupp.single 0 1)
    (h2 : s ≠ Finsupp.single 1 1) :
    2 ≤ s 0 + s 1 := by
  by_contra h_lt
  push_neg at h_lt
  by_cases hs0z : s 0 = 0
  · by_cases hs1z : s 1 = 0
    · apply h0
      ext i; fin_cases i
      · exact hs0z
      · exact hs1z
    · have hs1 : s 1 = 1 := by omega
      apply h2
      ext i; fin_cases i
      · simp [hs0z, Finsupp.single_apply]
      · simp [hs1, Finsupp.single_apply]
  · have hs0 : s 0 = 1 := by omega
    have hs1z : s 1 = 0 := by omega
    apply h1
    ext i; fin_cases i
    · simp [hs0, Finsupp.single_apply]
    · simp [hs1z, Finsupp.single_apply]

/-- An `MvPolynomial (Fin 2) ℕ` of total degree ≤ 1 evaluates to an affine
    function of its inputs. -/
theorem aeval_of_totalDegree_le_one
    (p : MvPolynomial (Fin 2) ℕ) (h : p.totalDegree ≤ 1) :
    ∃ α β γ : ℕ, ∀ a b : ℕ, MvPolynomial.aeval (![a, b] : Fin 2 → ℕ) p = α * a + β * b + γ := by
  classical
  refine ⟨p.coeff (Finsupp.single 0 1), p.coeff (Finsupp.single 1 1), p.coeff 0, ?_⟩
  intro a b
  have h_ne_01 : Finsupp.single (0 : Fin 2) 1 ≠ Finsupp.single 1 1 := by
    intro hcontra
    have := congrArg (· (0 : Fin 2)) hcontra
    simp [Finsupp.single_apply] at this
  have h_ne_0_s0 : (0 : Fin 2 →₀ ℕ) ≠ Finsupp.single (0 : Fin 2) 1 := by
    intro hcontra
    have := congrArg (· (0 : Fin 2)) hcontra
    simp [Finsupp.single_apply] at this
  have h_ne_0_s1 : (0 : Fin 2 →₀ ℕ) ≠ Finsupp.single (1 : Fin 2) 1 := by
    intro hcontra
    have := congrArg (· (1 : Fin 2)) hcontra
    simp [Finsupp.single_apply] at this
  have h_eq : p = MvPolynomial.C (p.coeff 0) +
                  MvPolynomial.C (p.coeff (Finsupp.single 0 1)) * MvPolynomial.X 0 +
                  MvPolynomial.C (p.coeff (Finsupp.single 1 1)) * MvPolynomial.X 1 := by
    apply MvPolynomial.ext
    intro s
    rw [MvPolynomial.coeff_add, MvPolynomial.coeff_add,
        MvPolynomial.coeff_C, MvPolynomial.coeff_C_mul, MvPolynomial.coeff_C_mul,
        MvPolynomial.coeff_X', MvPolynomial.coeff_X']
    by_cases hs : s = (0 : Fin 2 →₀ ℕ)
    · subst hs
      simp only [if_neg (Ne.symm h_ne_0_s0), if_neg (Ne.symm h_ne_0_s1),
                 mul_zero, add_zero, if_true, ite_true]
    · by_cases hs' : s = Finsupp.single (0 : Fin 2) 1
      · subst hs'
        simp only [if_neg h_ne_0_s0, if_neg (Ne.symm h_ne_01),
                   mul_zero, mul_one, zero_add, add_zero, if_true, ite_true]
      · by_cases hs'' : s = Finsupp.single (1 : Fin 2) 1
        · subst hs''
          simp only [if_neg h_ne_0_s1, if_neg h_ne_01,
                     mul_zero, mul_one, zero_add, add_zero, if_true, ite_true]
        · have h_sum_ge : 2 ≤ s 0 + s 1 := sum_ge_two_of_not_low hs hs' hs''
          have h_supp_sum : ∑ i ∈ s.support, s i = s 0 + s 1 := by
            rw [Finset.sum_subset s.support.subset_univ]
            · exact Fin.sum_univ_two _
            · intro i _ hi
              by_contra hne
              exact hi (Finsupp.mem_support_iff.mpr hne)
          have h_coeff : p.coeff s = 0 :=
            MvPolynomial.coeff_eq_zero_of_totalDegree_lt (by rw [h_supp_sum]; omega)
          rw [h_coeff, if_neg (fun heq => hs heq.symm),
              if_neg (fun heq => hs' heq.symm),
              if_neg (fun heq => hs'' heq.symm)]
          ring
  conv_lhs => rw [h_eq]
  rw [map_add, map_add, map_mul, map_mul]
  rw [MvPolynomial.aeval_C, MvPolynomial.aeval_C, MvPolynomial.aeval_C]
  rw [MvPolynomial.aeval_X, MvPolynomial.aeval_X]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Algebra.algebraMap_self_apply]
  ring

/-! ### The master theorem

  *For any polynomial `⊙ : ℕ × ℕ → ℕ`, NOT both `+` and `·` are in the
  clone of `⟨⊙, finite ℕ-constants⟩`.*

**Strategy** — case split on `p.totalDegree`:

* `p.totalDegree ≤ 1`: `⊙` is ℕ-affine (via `aeval_of_totalDegree_le_one`),
  so `affine_does_not_reach_mul` rules out `·`. (`polynomial_does_not_reach_mul_when_deg_le_one`.)

* `p.totalDegree ≥ 2`: show `⊙` doesn't reach `+`. Suppose `t` realizes
  `+`. Do strong induction on `t.size`. The base cases (`.var`, `.const`)
  are immediate. For `t = .op s u`, get the realizing polynomials
  `q_s`, `q_u` for the subterms and case-split:

  - **Both `q_s.totalDegree ≥ 1` and `q_u.totalDegree ≥ 1`**: by
    `bind₁_totalDegree_ge_of_nonconstant`, the realizing polynomial for
    `t` has totalDegree ≥ `p.totalDegree` ≥ 2. The growth bound then
    gives `aeval ![3, 3] t ≥ 3^2 = 9`, but `t` realizes `a + b` so this
    value equals `6`. Contradiction.

  - **`q_s.totalDegree = 0`**: `q_s = C c_s` for some `c_s : ℕ`, and the
    equation becomes `∀ a b, aeval ![c_s, aeval ![a, b] q_u] p = a + b`.
    Apply `const_subterm_yields_false_aux` (see below) with `q = q_u`
    and `ih` derived from the term-level induction hypothesis on `u`.

  - **`q_u.totalDegree = 0`**: `q_u = C c_u`. The equation becomes
    `∀ a b, aeval ![aeval ![a, b] q_s, c_u] p = a + b`. We reduce to
    the previous case via `swapPoly`: working with `swapPoly p` switches
    the roles of `X 0` and `X 1`, after which the constant subterm sits
    on the left. Apply `const_subterm_yields_false_aux` to `swapPoly p`.

The helper `const_subterm_yields_false_aux` handles "constant on the
left, `q` arbitrary" by case-splitting on `q.totalDegree`:

* `q.totalDegree ≥ 2`: R-dichotomy on `R(M) := aeval ![c, M] p`:
  - If `R(0) = R(1)`: `R` is constant in its second argument (no X 1
    monomial contributes), so the equation `R(U(a, b)) = a + b` forces
    `a + b` to be constant. Contradicts `(0,0)` vs `(0,1)`.
  - Else `R(0) < R(1)`: `R(M) ≥ M` for `M ≥ 1`. Taking `M_3 := aeval
    ![3, 3] q` gives `M_3 ≥ 9` (growth on `q`) and `R(M_3) ≥ M_3 ≥ 9`,
    but `R(M_3) = 6` from the equation. Contradiction.

* `q.totalDegree ≤ 1`: `q = αX 0 + βX 1 + γ` is affine.
  - If `α ≠ β`: **collision argument.** The points `(a, b) = (β, 0)`
    and `(0, α)` both give `U = αβ + γ`, but `a + b = β` vs `α`. Then
    `R(U(β, 0)) = β` and `R(U(0, α)) = α` with the LHS being the same
    `R`-value, forcing `α = β`. Contradiction.
  - If `α = β = 0`: `U` is constant `γ`, so `R(γ) = a + b` for varying
    `a + b`. Contradiction.
  - If `α = β ≥ 1`: the equation reduces to `R(αm + γ) = m` for all
    `m : ℕ`. Subcases:
    - `α = 1, γ = 0`: `q = X 0 + X 1`, so the subterm itself realizes
      `+`. Apply the term-level IH (passed in as `ih`).
    - `γ ≥ 1`: `R(γ) = 0` with `γ ≥ 1`. The ℕ-coefficient structure
      forces `R ≡ 0` (`aeval_zero_at_pos_imp_zero_everywhere`),
      contradicting `R(α + γ) = 1`.
    - `α ≥ 2, γ = 0`: monomial-count argument. `R(0) = 0` forces all
      X 1-free coefficients to be zero. `R(α) = 1` then sums to `1`,
      but each remaining term has factor `α^(d 1) ≥ 2`, so each is
      either `0` or `≥ 2`. No subset sums to `1`. Contradiction.

(Note: this restriction to *polynomial* `⊙` is essential. With
tag-based encoding `⟨t, v⟩ ∈ ℕ` via Cantor pairing, one can construct
a non-polynomial `⊙` whose clone contains both `+` and `·` — a
Sierpiński-style trick on the infinite carrier. The polynomial qualifier
rules out this decoding-based trick because decoding from Cantor pairs
is not polynomial.)
-/

/-! #### Piece 1: A `ℕ`-sum-vanishing utility

A sum of non-negative `ℕ` terms is zero iff every term is zero. Used
repeatedly in the no-cancellation arguments below.
-/

/-- For non-negative terms, `∑ f i = 0` iff every `f i = 0`. -/
private lemma sum_pos_nat_eq_zero_iff {ι : Type*} (s : Finset ι)
    (f : ι → ℕ) : ∑ i ∈ s, f i = 0 ↔ ∀ i ∈ s, f i = 0 := by
  classical
  refine ⟨fun h i hi => ?_, fun h => Finset.sum_eq_zero h⟩
  by_contra h_pos
  have : 0 < f i := Nat.pos_of_ne_zero h_pos
  have : 0 < ∑ j ∈ s, f j :=
    lt_of_lt_of_le this (Finset.single_le_sum (f := f) (fun _ _ => Nat.zero_le _) hi)
  omega

/-! #### Piece 2: Monomial-sum form of `aeval ![c, x] p` -/

/-- `aeval ![c, x] p` written as an explicit sum over `p`'s monomial support.
    Useful for term-by-term arguments about non-negative summands on `ℕ`. -/
private lemma aeval_pair_eq_monomial_sum (p : MvPolynomial (Fin 2) ℕ) (c x : ℕ) :
    MvPolynomial.aeval (![c, x] : Fin 2 → ℕ) p =
    ∑ d ∈ p.support, p.coeff d * c^(d 0) * x^(d 1) := by
  classical
  rw [show MvPolynomial.aeval (![c, x] : Fin 2 → ℕ) p =
        ∑ d ∈ p.support, p.coeff d * ∏ i ∈ d.support, (![c, x] : Fin 2 → ℕ) i ^ d i from by
    rw [MvPolynomial.aeval_def, MvPolynomial.eval₂_eq]
    simp [RingHom.id_apply]]
  apply Finset.sum_congr rfl
  intro d _
  have h_prod : ∏ i ∈ d.support, (![c, x] : Fin 2 → ℕ) i ^ d i = c^(d 0) * x^(d 1) := by
    calc ∏ i ∈ d.support, (![c, x] : Fin 2 → ℕ) i ^ d i
        = ∏ i ∈ (Finset.univ : Finset (Fin 2)), (![c, x] : Fin 2 → ℕ) i ^ d i := by
          apply Finset.prod_subset d.support.subset_univ
          intro i _ hi
          have : d i = 0 := by
            by_contra hne; exact hi (Finsupp.mem_support_iff.mpr hne)
          rw [this, pow_zero]
      _ = (![c, x] : Fin 2 → ℕ) 0 ^ d 0 * (![c, x] : Fin 2 → ℕ) 1 ^ d 1 :=
            Fin.prod_univ_two _
      _ = c ^ d 0 * x ^ d 1 := by simp
  rw [h_prod, ← mul_assoc]

/-! #### Piece 3: Vanishing along a line forces vanishing everywhere

If `aeval ![c, γ] p = 0` for `γ ≥ 1`, then `aeval ![c, M] p = 0` for every `M`.
This is the ℕ-coefficient "no-cancellation" content: a sum of non-negative
products equals zero only if each product is zero, and `γ^k ≥ 1` for any `k`
when `γ ≥ 1`, so the `M^k` parts can be replaced freely.
-/

private lemma aeval_zero_at_pos_imp_zero_everywhere
    (p : MvPolynomial (Fin 2) ℕ) (c γ : ℕ) (hγ : 1 ≤ γ)
    (h : MvPolynomial.aeval (![c, γ] : Fin 2 → ℕ) p = 0) :
    ∀ M : ℕ, MvPolynomial.aeval (![c, M] : Fin 2 → ℕ) p = 0 := by
  classical
  intro M
  rw [aeval_pair_eq_monomial_sum p c γ] at h
  rw [aeval_pair_eq_monomial_sum p c M]
  have h_each : ∀ d ∈ p.support, p.coeff d * c^(d 0) * γ^(d 1) = 0 :=
    (sum_pos_nat_eq_zero_iff _ _).mp h
  apply Finset.sum_eq_zero
  intro d hd
  have h_this := h_each d hd
  have hγ_pow_ne : γ^(d 1) ≠ 0 := pow_ne_zero _ (by omega)
  have h_cancel : p.coeff d * c^(d 0) = 0 := by
    rcases mul_eq_zero.mp h_this with h1 | h2
    · exact h1
    · exact absurd h2 hγ_pow_ne
  rw [h_cancel, zero_mul]

/-! #### Piece 4: Monotonicity of `aeval ![c, ·] p` in the second argument -/

private lemma aeval_pair_mono (p : MvPolynomial (Fin 2) ℕ) (c : ℕ) {M N : ℕ}
    (h : M ≤ N) :
    MvPolynomial.aeval (![c, M] : Fin 2 → ℕ) p ≤
    MvPolynomial.aeval (![c, N] : Fin 2 → ℕ) p := by
  classical
  rw [aeval_pair_eq_monomial_sum p c M, aeval_pair_eq_monomial_sum p c N]
  apply Finset.sum_le_sum
  intro d _
  exact Nat.mul_le_mul_left _ (Nat.pow_le_pow_left h _)

/-! #### Piece 5: Partition by X₁-dependence

Split `aeval ![c, x] p` into the part with no X₁-dependence (`d 1 = 0`, contributing
the same constant for all `x`) and the rest. This is the workhorse for both
"R-constant" and "R-grows" arguments below.
-/

private lemma aeval_pair_split_by_X1 (p : MvPolynomial (Fin 2) ℕ) (c x : ℕ) :
    MvPolynomial.aeval (![c, x] : Fin 2 → ℕ) p =
    (∑ d ∈ p.support.filter (fun d => d 1 = 0), p.coeff d * c^(d 0)) +
    (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * x^(d 1)) := by
  classical
  rw [aeval_pair_eq_monomial_sum p c x]
  have h_part : p.support =
      p.support.filter (fun d => d 1 = 0) ∪ p.support.filter (fun d => 1 ≤ d 1) := by
    ext d
    simp only [Finset.mem_union, Finset.mem_filter]
    constructor
    · intro hd
      rcases Nat.eq_zero_or_pos (d 1) with h0 | h1
      · left; exact ⟨hd, h0⟩
      · right; exact ⟨hd, h1⟩
    · rintro (⟨h, _⟩ | ⟨h, _⟩) <;> exact h
  have h_disj : Disjoint (p.support.filter (fun d => d 1 = 0))
                         (p.support.filter (fun d => 1 ≤ d 1)) := by
    rw [Finset.disjoint_filter]
    intros d _ h0 h1; omega
  conv_lhs => rw [h_part]
  rw [Finset.sum_union h_disj]
  congr 1
  apply Finset.sum_congr rfl
  intro d hd
  rw [Finset.mem_filter] at hd
  rw [hd.2, pow_zero, mul_one]

/-! #### Piece 6: The R-dichotomy

Define `R(M) := aeval ![c, M] p`. Then either `R` is constant (`R(M) = R(0)` for all M),
or `R(M) ≥ M` for `M ≥ 1`. The test is `R(0)` vs `R(1)`: if equal, constant; if `<`,
grows at least linearly.
-/

/-- If `R(0) = R(1)`, then `R(M) = R(0)` for all `M`. -/
private lemma aeval_pair_const_of_eq_at_one
    {p : MvPolynomial (Fin 2) ℕ} {c : ℕ}
    (h_eq : MvPolynomial.aeval (![c, 0] : Fin 2 → ℕ) p =
            MvPolynomial.aeval (![c, 1] : Fin 2 → ℕ) p) :
    ∀ M, MvPolynomial.aeval (![c, M] : Fin 2 → ℕ) p =
         MvPolynomial.aeval (![c, 0] : Fin 2 → ℕ) p := by
  classical
  intro M
  rw [aeval_pair_split_by_X1 p c M, aeval_pair_split_by_X1 p c 0,
      aeval_pair_split_by_X1 p c 1] at *
  -- At x = 0, S1 part is 0
  have h_S1_at_0 :
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * 0^(d 1)) = 0 := by
    apply Finset.sum_eq_zero
    intro d hd
    rw [Finset.mem_filter] at hd
    rw [zero_pow (Nat.pos_iff_ne_zero.mp hd.2), mul_zero]
  -- At x = 1, S1 part equals ∑ coeff
  have h_S1_at_1 :
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * 1^(d 1)) =
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0)) := by
    apply Finset.sum_congr rfl
    intro d _; rw [one_pow, mul_one]
  rw [h_S1_at_0, add_zero] at h_eq
  rw [h_S1_at_1] at h_eq
  -- h_eq : S0 = S0 + S1coeffs, so ∑ S1 coeffs = 0
  have h_S1_zero : (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0)) = 0 :=
    by omega
  -- Each term is 0
  have h_each : ∀ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) = 0 :=
    (sum_pos_nat_eq_zero_iff _ _).mp h_S1_zero
  -- So at any x = M, S1 part is 0
  have h_S1_at_M :
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * M^(d 1)) = 0 := by
    apply Finset.sum_eq_zero
    intro d hd
    rw [show p.coeff d * c^(d 0) * M^(d 1) = (p.coeff d * c^(d 0)) * M^(d 1) from rfl,
        h_each d hd, zero_mul]
  rw [h_S1_at_M, add_zero, h_S1_at_0, add_zero]

/-- If `R(0) < R(1)`, then `R(M) ≥ M` for `M ≥ 1`. -/
private lemma aeval_pair_ge_M_of_lt_at_one
    {p : MvPolynomial (Fin 2) ℕ} {c : ℕ}
    (h_lt : MvPolynomial.aeval (![c, 0] : Fin 2 → ℕ) p <
            MvPolynomial.aeval (![c, 1] : Fin 2 → ℕ) p)
    {M : ℕ} (hM : 1 ≤ M) :
    M ≤ MvPolynomial.aeval (![c, M] : Fin 2 → ℕ) p := by
  classical
  rw [aeval_pair_split_by_X1 p c M]
  rw [aeval_pair_split_by_X1 p c 0, aeval_pair_split_by_X1 p c 1] at h_lt
  have h_S1_at_0 :
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * 0^(d 1)) = 0 := by
    apply Finset.sum_eq_zero
    intro d hd
    rw [Finset.mem_filter] at hd
    rw [zero_pow (Nat.pos_iff_ne_zero.mp hd.2), mul_zero]
  have h_S1_at_1 :
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * 1^(d 1)) =
      (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0)) := by
    apply Finset.sum_congr rfl
    intro d _; rw [one_pow, mul_one]
  rw [h_S1_at_0, add_zero] at h_lt
  rw [h_S1_at_1] at h_lt
  -- h_lt: S0 < S0 + S1coeffs, so ∑ S1 coeffs ≥ 1
  have h_S1_pos : 1 ≤ ∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) := by
    omega
  -- At M: each term ≥ p.coeff d * c^(d 0) * M (since M^(d 1) ≥ M for d 1 ≥ 1, M ≥ 1)
  have h_term_bound : ∀ d ∈ p.support.filter (fun d => 1 ≤ d 1),
      p.coeff d * c^(d 0) * M ≤ p.coeff d * c^(d 0) * M^(d 1) := by
    intro d hd
    rw [Finset.mem_filter] at hd
    apply Nat.mul_le_mul_left
    calc M = M^1 := (pow_one M).symm
      _ ≤ M^(d 1) := Nat.pow_le_pow_right hM hd.2
  have h_S1_M_bound :
      M * (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0)) ≤
      ∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * M^(d 1) := by
    rw [Finset.mul_sum]
    apply Finset.sum_le_sum
    intro d hd
    have := h_term_bound d hd
    calc M * (p.coeff d * c^(d 0)) = p.coeff d * c^(d 0) * M := by ring
      _ ≤ p.coeff d * c^(d 0) * M^(d 1) := this
  calc M = M * 1 := by ring
    _ ≤ M * (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0)) :=
        Nat.mul_le_mul_left _ h_S1_pos
    _ ≤ ∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * M^(d 1) :=
        h_S1_M_bound
    _ ≤ (∑ d ∈ p.support.filter (fun d => d 1 = 0), p.coeff d * c^(d 0)) +
        (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1), p.coeff d * c^(d 0) * M^(d 1)) := by
      omega

/-! #### Piece 7: Swap lemmas for `Fin 2` arguments

To handle the "q_u constant" case symmetrically to "q_s constant", we use the
swap polynomial `swap p := bind₁ ![X 1, X 0] p`. This swaps the roles of X 0
and X 1, letting us reduce the q_u case to a q_s case for a different
polynomial.
-/

private noncomputable def swapPoly (p : MvPolynomial (Fin 2) ℕ) : MvPolynomial (Fin 2) ℕ :=
  MvPolynomial.bind₁ (![MvPolynomial.X 1, MvPolynomial.X 0] : Fin 2 → MvPolynomial (Fin 2) ℕ) p

private lemma aeval_swapPoly (p : MvPolynomial (Fin 2) ℕ) (a b : ℕ) :
    MvPolynomial.aeval (![a, b] : Fin 2 → ℕ) (swapPoly p) =
    MvPolynomial.aeval (![b, a] : Fin 2 → ℕ) p := by
  unfold swapPoly
  rw [MvPolynomial.aeval_bind₁]
  have h_args : (fun i : Fin 2 => MvPolynomial.aeval (![a, b] : Fin 2 → ℕ)
      ((![MvPolynomial.X 1, MvPolynomial.X 0] : Fin 2 → MvPolynomial (Fin 2) ℕ) i)) =
      (![b, a] : Fin 2 → ℕ) := by
    funext i; fin_cases i <;> simp
  rw [h_args]

private lemma swapPoly_totalDegree_ge (p : MvPolynomial (Fin 2) ℕ) :
    p.totalDegree ≤ (swapPoly p).totalDegree := by
  unfold swapPoly
  apply bind₁_totalDegree_ge_of_nonconstant
  · show 1 ≤ (MvPolynomial.X 1 : MvPolynomial (Fin 2) ℕ).totalDegree
    rw [MvPolynomial.totalDegree_X]
  · show 1 ≤ (MvPolynomial.X 0 : MvPolynomial (Fin 2) ℕ).totalDegree
    rw [MvPolynomial.totalDegree_X]

/-! #### Piece 8: The constant-left helper

If `q_s = C c_s` and the resulting equation `aeval ![c, aeval ![a, b] q] p = a + b`
holds for all `a, b`, then we derive a contradiction (using `ih` for the
"q = X 0 + X 1" subcase). Case analysis on `q.totalDegree`:
- `q.totalDegree ≥ 2`: R-dichotomy (R const ⇒ a+b const, contradiction;
  R non-const ⇒ R(M_3) ≥ M_3 ≥ 9 contradicts R(M_3) = 6).
- `q.totalDegree ≤ 1`: q is affine `αX 0 + βX 1 + γ`.
  - α ≠ β: collision at (β, 0) vs (0, α).
  - α = β: equation reduces to `R(αm + γ) = m`. Subcases via polynomial
    coefficient analysis or IH.
-/

private theorem const_subterm_yields_false_aux
    {p : MvPolynomial (Fin 2) ℕ}
    {c : ℕ} {q : MvPolynomial (Fin 2) ℕ}
    (h_eq : ∀ a b : ℕ,
      MvPolynomial.aeval (![c, MvPolynomial.aeval ![a, b] q] : Fin 2 → ℕ) p = a + b)
    (ih : ¬ ∀ a b : ℕ, MvPolynomial.aeval (![a, b] : Fin 2 → ℕ) q = a + b) :
    False := by
  classical
  by_cases h_q_deg_ge_two : 2 ≤ q.totalDegree
  · -- q.totalDegree ≥ 2: R-dichotomy
    by_cases h_R01 : MvPolynomial.aeval (![c, 0] : Fin 2 → ℕ) p =
                     MvPolynomial.aeval (![c, 1] : Fin 2 → ℕ) p
    · -- R constant: equation forces a+b constant, contradiction
      have h_R_const := aeval_pair_const_of_eq_at_one h_R01
      have h_at_0_0 := h_eq 0 0
      have h_at_0_1 := h_eq 0 1
      rw [h_R_const (MvPolynomial.aeval ![0, 0] q)] at h_at_0_0
      rw [h_R_const (MvPolynomial.aeval ![0, 1] q)] at h_at_0_1
      omega
    · -- R non-constant: growth bound contradicts a+b = O(n)
      have h_R_lt : MvPolynomial.aeval (![c, 0] : Fin 2 → ℕ) p <
                    MvPolynomial.aeval (![c, 1] : Fin 2 → ℕ) p := by
        have h_mono : MvPolynomial.aeval (![c, 0] : Fin 2 → ℕ) p ≤
                      MvPolynomial.aeval (![c, 1] : Fin 2 → ℕ) p :=
          aeval_pair_mono p c (Nat.zero_le 1)
        omega
      have h_q_ne : q ≠ 0 := fun h_zero => by
        rw [h_zero, MvPolynomial.totalDegree_zero] at h_q_deg_ge_two; omega
      have h_M3_ge_9 : 9 ≤ MvPolynomial.aeval (![3, 3] : Fin 2 → ℕ) q := by
        have h_growth := aeval_n_n_ge_n_pow_totalDegree q h_q_ne 3 (by norm_num)
        calc 9 = 3^2 := by norm_num
          _ ≤ 3^q.totalDegree := Nat.pow_le_pow_right (by norm_num) h_q_deg_ge_two
          _ ≤ MvPolynomial.aeval ![3, 3] q := h_growth
      have h_M3_pos : 1 ≤ MvPolynomial.aeval (![3, 3] : Fin 2 → ℕ) q := by omega
      have h_R_M3_ge :
          MvPolynomial.aeval (![3, 3] : Fin 2 → ℕ) q ≤
          MvPolynomial.aeval (![c, MvPolynomial.aeval ![3, 3] q] : Fin 2 → ℕ) p :=
        aeval_pair_ge_M_of_lt_at_one h_R_lt h_M3_pos
      have h_R_M3_eq := h_eq 3 3
      omega
  · -- q.totalDegree ≤ 1: q is affine
    push_neg at h_q_deg_ge_two
    have h_q_deg_le_one : q.totalDegree ≤ 1 := by omega
    obtain ⟨α, β, γ, h_q_aff⟩ := aeval_of_totalDegree_le_one q h_q_deg_le_one
    by_cases h_αβ : α = β
    · -- α = β: equation reduces to ∀ m, aeval ![c, α*m + γ] p = m
      have h_R_line : ∀ m : ℕ,
          MvPolynomial.aeval (![c, α * m + γ] : Fin 2 → ℕ) p = m := by
        intro m
        have h_em := h_eq m 0
        have h_aff_m_0 : MvPolynomial.aeval (![m, 0] : Fin 2 → ℕ) q = α * m + γ := by
          rw [h_q_aff m 0]; ring
        rw [h_aff_m_0] at h_em; omega
      by_cases h_α : α = 0
      · -- α = β = 0: U constant
        have h0 := h_R_line 0
        have h1 := h_R_line 1
        simp only [h_α, zero_mul, zero_add] at h0 h1
        omega
      · push_neg at h_α
        by_cases h_γ : γ = 0
        · subst h_γ
          by_cases h_α_one : α = 1
          · -- α = β = 1, γ = 0: q = X 0 + X 1, IH contradiction
            apply ih
            intro a b
            have h_β_one : β = 1 := h_αβ ▸ h_α_one
            rw [h_q_aff a b, h_α_one, h_β_one]
            ring
          · -- α ≥ 2, γ = 0: monomial-count argument
            have h_α_two : 2 ≤ α := by omega
            have h_R_0 := h_R_line 0
            have h_R_α := h_R_line 1
            simp only [mul_zero, mul_one, add_zero, zero_add] at h_R_0 h_R_α
            rw [aeval_pair_split_by_X1 p c 0] at h_R_0
            rw [aeval_pair_split_by_X1 p c α] at h_R_α
            have h_S1_at_0 :
                (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1),
                  p.coeff d * c^(d 0) * 0^(d 1)) = 0 := by
              apply Finset.sum_eq_zero
              intro d hd
              rw [Finset.mem_filter] at hd
              rw [zero_pow (Nat.pos_iff_ne_zero.mp hd.2), mul_zero]
            rw [h_S1_at_0, add_zero] at h_R_0
            have h_S0_each : ∀ d ∈ p.support.filter (fun d => d 1 = 0),
                p.coeff d * c^(d 0) = 0 :=
              (sum_pos_nat_eq_zero_iff _ _).mp h_R_0
            have h_S0_at_α :
                (∑ d ∈ p.support.filter (fun d => d 1 = 0), p.coeff d * c^(d 0)) = 0 :=
              Finset.sum_eq_zero h_S0_each
            rw [h_S0_at_α, zero_add] at h_R_α
            have key : ∀ d ∈ p.support.filter (fun d => 1 ≤ d 1),
                p.coeff d * c^(d 0) * α^(d 1) = 0 ∨
                α ≤ p.coeff d * c^(d 0) * α^(d 1) := by
              intro d hd
              rw [Finset.mem_filter] at hd
              by_cases h_factor : p.coeff d * c^(d 0) = 0
              · left; rw [h_factor, zero_mul]
              · right
                have h_factor_pos : 1 ≤ p.coeff d * c^(d 0) := Nat.pos_of_ne_zero h_factor
                have h_alpha_pow : α ≤ α^(d 1) :=
                  calc α = α^1 := (pow_one α).symm
                    _ ≤ α^(d 1) := Nat.pow_le_pow_right (by omega) hd.2
                calc α = 1 * α := (one_mul α).symm
                  _ ≤ p.coeff d * c^(d 0) * α := Nat.mul_le_mul_right _ h_factor_pos
                  _ ≤ p.coeff d * c^(d 0) * α^(d 1) := Nat.mul_le_mul_left _ h_alpha_pow
            by_cases h_all_zero : ∀ d ∈ p.support.filter (fun d => 1 ≤ d 1),
                                   p.coeff d * c^(d 0) * α^(d 1) = 0
            · have h_sum_zero : (∑ d ∈ p.support.filter (fun d => 1 ≤ d 1),
                  p.coeff d * c^(d 0) * α^(d 1)) = 0 :=
                Finset.sum_eq_zero h_all_zero
              omega
            · push_neg at h_all_zero
              obtain ⟨d₀, hd₀_mem, hd₀_nonzero⟩ := h_all_zero
              rcases key d₀ hd₀_mem with h_zero | h_ge
              · exact hd₀_nonzero h_zero
              · have h_sum_ge :
                    α ≤ ∑ d ∈ p.support.filter (fun d => 1 ≤ d 1),
                          p.coeff d * c^(d 0) * α^(d 1) :=
                  calc α ≤ p.coeff d₀ * c^(d₀ 0) * α^(d₀ 1) := h_ge
                    _ ≤ _ := Finset.single_le_sum
                          (f := fun d => p.coeff d * c^(d 0) * α^(d 1))
                          (fun _ _ => Nat.zero_le _) hd₀_mem
                omega
        · push_neg at h_γ
          have h_γ_pos : 1 ≤ γ := Nat.pos_of_ne_zero h_γ
          have h_R_γ := h_R_line 0
          simp only [mul_zero, zero_add] at h_R_γ
          have h_R_zero := aeval_zero_at_pos_imp_zero_everywhere p c γ h_γ_pos h_R_γ
          have h_R_αγ := h_R_line 1
          simp only [mul_one] at h_R_αγ
          rw [h_R_zero (α + γ)] at h_R_αγ
          omega
    · -- α ≠ β: collision argument
      have h_coll : MvPolynomial.aeval (![β, 0] : Fin 2 → ℕ) q =
                    MvPolynomial.aeval (![0, α] : Fin 2 → ℕ) q := by
        rw [h_q_aff β 0, h_q_aff 0 α]; ring
      have h_a := h_eq β 0
      have h_b := h_eq 0 α
      rw [h_coll] at h_a
      omega

/-! #### Piece 9: The hard half (deg ≥ 2)

For a polynomial `⊙` with corresponding polynomial of totalDegree ≥ 2, `⊙` does
not reach `+`. The proof is by strong induction on the term size. The induction
step (`.op s u`) splits on the totalDegrees of the realizing polynomials for `s`
and `u`:
- Both ≥ 1: `bind₁_totalDegree_ge_of_nonconstant` gives `q.totalDegree ≥ 2`,
  contradicting the growth bound for `q` realizing `a + b`.
- `q_s.totalDegree = 0`: apply `const_subterm_yields_false_aux` directly.
- `q_u.totalDegree = 0`: apply `const_subterm_yields_false_aux` after swapping
  the polynomial roles via `swapPoly`.
-/

theorem polynomial_does_not_reach_add_when_deg_ge_two
    {p : MvPolynomial (Fin 2) ℕ} (h_deg : 2 ≤ p.totalDegree)
    {op : ℕ → ℕ → ℕ} (hop : ∀ a b, op a b = MvPolynomial.aeval ![a, b] p) :
    ¬ Reaches op addFn := by
  rintro ⟨t, h_t⟩
  suffices key : ∀ n, ∀ t : Term (Fin 2),
      t.size = n → ¬ ∀ a b : ℕ, t.eval op ![a, b] = a + b by
    exact key t.size t rfl (fun a b => h_t a b)
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro t h_size h_t
    match t, h_size, h_t with
    | .var i, _, h_t =>
      fin_cases i
      · have := h_t 0 1; simp [Term.eval] at this
      · have := h_t 1 0; simp [Term.eval] at this
    | .const c, _, h_t =>
      have h0 := h_t 0 0
      have h1 := h_t 0 1
      simp [Term.eval] at h0 h1
      omega
    | .op s u, h_size, h_t =>
      have h_s_size : s.size < n := by simp [Term.size] at h_size; omega
      have h_u_size : u.size < n := by simp [Term.size] at h_size; omega
      have ih_s : ¬ ∀ a b, s.eval op ![a, b] = a + b := ih s.size h_s_size s rfl
      have ih_u : ¬ ∀ a b, u.eval op ![a, b] = a + b := ih u.size h_u_size u rfl
      have hpoly : IsPolynomialNat op := ⟨p, hop⟩
      obtain ⟨q_s, hq_s⟩ := polynomial_term_realizes_poly hpoly s
      obtain ⟨q_u, hq_u⟩ := polynomial_term_realizes_poly hpoly u
      -- The realizing polynomial for t
      set q := MvPolynomial.bind₁ (![q_s, q_u] : Fin 2 → MvPolynomial (Fin 2) ℕ) p
        with hq_def
      have h_q_realizes : ∀ a b : ℕ,
          MvPolynomial.aeval (![a, b] : Fin 2 → ℕ) q = a + b := by
        intro a b
        rw [hq_def, MvPolynomial.aeval_bind₁]
        have h_args : (fun i : Fin 2 => MvPolynomial.aeval (![a, b] : Fin 2 → ℕ)
            ((![q_s, q_u] : Fin 2 → MvPolynomial (Fin 2) ℕ) i)) =
            ![s.eval op ![a, b], u.eval op ![a, b]] := by
          funext i; fin_cases i
          · simp [hq_s]
          · simp [hq_u]
        rw [h_args]
        have h_op_eq := hop (s.eval op ![a, b]) (u.eval op ![a, b])
        rw [← h_op_eq]
        exact h_t a b
      -- Case on q_s.totalDegree
      by_cases h_qs_pos : 1 ≤ q_s.totalDegree
      · by_cases h_qu_pos : 1 ≤ q_u.totalDegree
        · -- Both non-constant: bind₁ degree lemma forces q.totalDegree ≥ 2
          have h_q_ne : q ≠ 0 := fun h_zero => by
            have := h_q_realizes 1 1
            rw [h_zero] at this; simp at this
          have h_q_deg_ge : p.totalDegree ≤ q.totalDegree :=
            bind₁_totalDegree_ge_of_nonconstant p q_s q_u h_qs_pos h_qu_pos
          have h_growth := aeval_n_n_ge_n_pow_totalDegree q h_q_ne 3 (by norm_num)
          rw [h_q_realizes 3 3] at h_growth
          have h_pow_ge : 9 ≤ 3^q.totalDegree := by
            calc 9 = 3^2 := by norm_num
              _ ≤ 3^q.totalDegree := Nat.pow_le_pow_right (by norm_num) (by omega)
          omega
        · -- q_u constant: q_u = C c_u. Swap and apply const helper.
          push_neg at h_qu_pos
          have h_qu_zero : q_u.totalDegree = 0 := Nat.lt_one_iff.mp h_qu_pos
          obtain ⟨c_u, h_qu_eq⟩ : ∃ c, q_u = MvPolynomial.C c :=
            ⟨q_u.coeff 0, MvPolynomial.totalDegree_eq_zero_iff_eq_C.mp h_qu_zero⟩
          -- Use swapPoly to reduce to const-left helper
          apply const_subterm_yields_false_aux (p := swapPoly p) (c := c_u) (q := q_s)
          · intro a b
            -- Goal: aeval ![c_u, aeval ![a, b] q_s] (swapPoly p) = a + b
            rw [aeval_swapPoly]
            -- Goal: aeval ![aeval ![a, b] q_s, c_u] p = a + b
            have h_qab : MvPolynomial.aeval (![a, b] : Fin 2 → ℕ) q = a + b := h_q_realizes a b
            rw [hq_def, h_qu_eq] at h_qab
            rw [MvPolynomial.aeval_bind₁] at h_qab
            have h_args' : (fun i : Fin 2 => MvPolynomial.aeval (![a, b] : Fin 2 → ℕ)
                ((![q_s, MvPolynomial.C c_u] : Fin 2 → MvPolynomial (Fin 2) ℕ) i)) =
                ![MvPolynomial.aeval ![a, b] q_s, c_u] := by
              funext i; fin_cases i
              · simp
              · simp
            rw [h_args'] at h_qab
            exact h_qab
          · -- ih: ¬ ∀ a b, aeval ![a, b] q_s = a + b
            intro h_contra
            apply ih_s
            intro a b
            rw [hq_s]
            exact h_contra a b
      · -- q_s constant: q_s = C c_s. Apply const helper directly.
        push_neg at h_qs_pos
        have h_qs_zero : q_s.totalDegree = 0 := Nat.lt_one_iff.mp h_qs_pos
        obtain ⟨c_s, h_qs_eq⟩ : ∃ c, q_s = MvPolynomial.C c :=
          ⟨q_s.coeff 0, MvPolynomial.totalDegree_eq_zero_iff_eq_C.mp h_qs_zero⟩
        apply const_subterm_yields_false_aux (p := p) (c := c_s) (q := q_u)
        · intro a b
          have h_qab : MvPolynomial.aeval (![a, b] : Fin 2 → ℕ) q = a + b := h_q_realizes a b
          rw [hq_def, h_qs_eq] at h_qab
          rw [MvPolynomial.aeval_bind₁] at h_qab
          have h_args' : (fun i : Fin 2 => MvPolynomial.aeval (![a, b] : Fin 2 → ℕ)
              ((![MvPolynomial.C c_s, q_u] : Fin 2 → MvPolynomial (Fin 2) ℕ) i)) =
              ![c_s, MvPolynomial.aeval ![a, b] q_u] := by
            funext i; fin_cases i
            · simp
            · simp
          rw [h_args'] at h_qab
          exact h_qab
        · intro h_contra
          apply ih_u
          intro a b
          rw [hq_u]
          exact h_contra a b

/-! #### Piece 10: The easy half (deg ≤ 1) -/

/-- A polynomial operator of total degree ≤ 1 is ℕ-affine. -/
theorem polynomial_is_affine_of_deg_le_one
    {p : MvPolynomial (Fin 2) ℕ} (h_deg : p.totalDegree ≤ 1)
    {op : ℕ → ℕ → ℕ} (hop : ∀ a b, op a b = MvPolynomial.aeval ![a, b] p) :
    IsNatAffine op := by
  obtain ⟨α, β, γ, h_aff⟩ := aeval_of_totalDegree_le_one p h_deg
  exact ⟨α, β, γ, fun x y => by rw [hop x y]; exact h_aff x y⟩

/-- Easy half: a polynomial `⊙` of totalDegree ≤ 1 does not reach `·`. -/
theorem polynomial_does_not_reach_mul_when_deg_le_one
    {p : MvPolynomial (Fin 2) ℕ} (h_deg : p.totalDegree ≤ 1)
    {op : ℕ → ℕ → ℕ} (hop : ∀ a b, op a b = MvPolynomial.aeval ![a, b] p) :
    ¬ Reaches op mulFn :=
  affine_does_not_reach_mul (polynomial_is_affine_of_deg_le_one h_deg hop)

/-! #### Piece 11: Headline theorem

Combining the two halves: for any polynomial `⊙` on `ℕ`, NOT both `+` and `·`
lie in the clone of `⟨⊙, ℕ-constants⟩`.
-/

/-- **Headline theorem.** For any polynomial binary operator `⊙ : ℕ × ℕ → ℕ`,
    NOT both `+` and `·` lie in the clone of `⟨⊙, ℕ-constants⟩`. -/
theorem polynomial_does_not_reach_both
    {op : ℕ → ℕ → ℕ} (h : IsPolynomialNat op) :
    ¬ (Reaches op addFn ∧ Reaches op mulFn) := by
  obtain ⟨p, hp⟩ := h
  by_cases h_deg : p.totalDegree ≤ 1
  · rintro ⟨_, h_mul⟩
    exact polynomial_does_not_reach_mul_when_deg_le_one h_deg hp h_mul
  · push_neg at h_deg
    rintro ⟨h_add, _⟩
    exact polynomial_does_not_reach_add_when_deg_ge_two h_deg hp h_add

end PolyClone.Naturals
